on: "3.2"

services:
  database:
    image: dockersamples/atseadb
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    networks:
      - back-tier
    secrets:
      - postgres_password
    deploy:
      placement:
        constraints:
          - 'node.role == worker'

  appserver:
    image: dockersamples/atseaapp:latest-sophia 
    ports:
      - "80:8080" 
    networks:
      - front-tier
      - back-tier
      - payment
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - postgres_password

  payment_gateway:
    image: dockersamples/atseapayment
    secrets:
      - source: payment_token
        target: payment_token
    networks:
      - payment
    deploy:
      placement:
        constraints:
          - 'node.role == worker'

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
    driver_opts:
      encrypted: 'yes'

secrets:
  postgres_password:
    external: true
  payment_token:
    external: true
